services:
  video-player:
    build: .
    container_name: video-player
    ports:
      - "8080:8080"
    environment:
      - APP_CONFIG=/config/config.yaml
    volumes:
      - ./config:/config
      - ./media:/media
    restart: unless-stopped
